import { resolveSourceIcon } from "../../shared/sourceCatalog";

function buildSources(labels = []) {
  return labels.map((label) => ({
    label,
    icon: resolveSourceIcon(label),
  }));
}

function createFlow({ steps = [], stepDataByStateKey = {} } = {}) {
  const normalizedSteps = steps.map((step) => ({ ...step }));

  return {
    steps: normalizedSteps,
    stepStateOrder: normalizedSteps.map((step) => String(step.stateKey)),
    stepDataByStateKey: { ...stepDataByStateKey },
    buildStep: normalizedSteps.length + 1,
  };
}

export const DEFAULT_ASSISTANT_FLOW = createFlow({
  steps: [
    {
      id: 2,
      stateKey: "2",
      type: "lookup",
      title: "SP GetAudit Data",
      builderTitle: "Get SP Audit Data",
      sources: buildSources(["SharePoint"]),
      comments: [
        { author: "You", body: "Confirm this should run every weekday morning.", stamp: "Feb 26, 9:05 AM" },
      ],
      detailsCollapsed: false,
      connections: [3],
      x: 0,
      y: 84,
    },
    {
      id: 3,
      stateKey: "3",
      type: "code",
      title: "Prune Audit Data",
      rowKeys: ["Operation", "Target", "Code"],
      comments: [
        { author: "You", body: "Delete anything older than one week.", stamp: "Feb 26, 9:06 AM" },
      ],
      ivySays: "This code step removes SharePoint audit rows older than seven days.",
      detailsCollapsed: false,
      connections: [4],
      x: 0,
      y: 168,
    },
    {
      id: 4,
      stateKey: "4",
      type: "message",
      title: "Email Audit List",
      rowKeys: ["Message", "Destination", "Recipients/Channel"],
      comments: [
        { author: "You", body: "Use this as the final delivery step.", stamp: "Feb 26, 9:07 AM" },
      ],
      ivySays: "This message step sends the summarized audit result to your configured recipients.",
      detailsCollapsed: false,
      connections: [],
      x: 0,
      y: 252,
    },
  ],
  stepDataByStateKey: {
    "2": {
      source: "SharePoint",
      list: "SP GetAudit",
      code: "Get yesterday's SharePoint audit activity if present.",
    },
    "3": {
      operation: "Delete old audit records",
      target: "SP GetAudit",
      runtime: "SQL",
      code: "DELETE FROM [SP GetAudit] WHERE [Created] < DATEADD(day, -7, GETUTCDATE())",
    },
    "4": {
      action: "Send Daily Audit Summary",
      channel: "Email",
      recipients: "Security Team",
      payload: "Daily audit summary template",
    },
  },
});

export const MOCK_ASSISTANT_FLOWS_BY_ID = {
  "1": createFlow({
    steps: [
      {
        id: 2,
        stateKey: "2",
        type: "lookup",
        title: "Collect Identity Signals",
        builderTitle: "Collect Identity Signals",
        sources: buildSources(["Microsoft 365", "Cisco Umbrella"]),
        ivySays: "This lookup gathers identity and sign-in risk signals from your connected identity tools.",
        detailsCollapsed: false,
        connections: [3],
        x: 0,
        y: 84,
      },
      {
        id: 3,
        stateKey: "3",
        type: "code",
        title: "Prioritize Identity Risks",
        rowKeys: ["Operation", "Target", "Code"],
        ivySays: "This step explains why each identity finding matters and prioritizes next actions.",
        detailsCollapsed: false,
        connections: [4],
        x: 0,
        y: 168,
      },
      {
        id: 4,
        stateKey: "4",
        type: "alert",
        title: "Escalate High-Risk Findings",
        ivySays: "This alert only fires when critical identity findings need review or escalation.",
        detailsCollapsed: false,
        connections: [],
        x: 0,
        y: 252,
      },
    ],
    stepDataByStateKey: {
      "2": {
        source: "Microsoft 365, Cisco Umbrella",
        list: "Users, roles, sign-ins, and external access",
        code: "Pull admin role assignments, MFA status, inactive licensed users, external accounts with broad access, and risky sign-ins from the last 24 hours.",
      },
      "3": {
        operation: "Score and explain identity risk",
        target: "Identity signal set",
        runtime: "Ivy Logic",
        code: "Rank findings by severity and include plain-English reasoning plus suggested next step (review, escalate, or document).",
      },
      "4": {
        condition: "Any high-severity identity risk exists",
        severity: "High",
        channels: "Ivy Inbox + Email",
        recipients: "Security Team",
      },
    },
  }),
  "2": createFlow({
    steps: [
      {
        id: 2,
        stateKey: "2",
        type: "lookup",
        title: "Watch Privileged Changes",
        builderTitle: "Watch Privileged Changes",
        sources: buildSources(["Microsoft 365", "Entra ID"]),
        ivySays: "This step monitors new elevated-access assignments from identity audit logs.",
        detailsCollapsed: false,
        connections: [3],
        x: 0,
        y: 84,
      },
      {
        id: 3,
        stateKey: "3",
        type: "alert",
        title: "Flag Unexpected Assignments",
        ivySays: "This alert highlights risky privilege grants and asks whether each change was expected.",
        detailsCollapsed: false,
        connections: [4],
        x: 0,
        y: 168,
      },
      {
        id: 4,
        stateKey: "4",
        type: "message",
        title: "Send Daily Privilege Summary",
        rowKeys: ["Message", "Destination", "Recipients/Channel"],
        ivySays: "This message sends a concise daily recap of privileged access changes.",
        detailsCollapsed: false,
        connections: [],
        x: 0,
        y: 252,
      },
    ],
    stepDataByStateKey: {
      "2": {
        source: "Microsoft 365",
        list: "Entra ID audit logs",
        code: "Track new privileged role assignments and enrich with MFA status and last access review timestamp.",
      },
      "3": {
        condition: "A new privileged role assignment is detected",
        severity: "High",
        channels: "Ivy Inbox",
        recipients: "Identity Admins",
      },
      "4": {
        action: "Send daily privileged access digest with context and 'Was this expected?' prompt.",
        channel: "Email",
        recipients: "Security Team",
        payload: "Include who changed, assigned role, MFA status, and review recency.",
      },
    },
  }),
  "3": createFlow({
    steps: [
      {
        id: 2,
        stateKey: "2",
        type: "lookup",
        title: "Collect Device Health Signals",
        builderTitle: "Collect Device Signals",
        sources: buildSources(["Kaseya VSA", "Sophos XDR", "Sophos EDR"]),
        ivySays: "This step pulls management, protection, and encryption posture across endpoint tools.",
        detailsCollapsed: false,
        connections: [3],
        x: 0,
        y: 84,
      },
      {
        id: 3,
        stateKey: "3",
        type: "code",
        title: "Classify Endpoint Issues",
        rowKeys: ["Operation", "Target", "Code"],
        ivySays: "This logic groups endpoint findings into operational and security categories.",
        detailsCollapsed: false,
        connections: [4],
        x: 0,
        y: 168,
      },
      {
        id: 4,
        stateKey: "4",
        type: "message",
        title: "Deliver Device Attention List",
        ivySays: "This step sends the final prioritized endpoint list to operations and security.",
        detailsCollapsed: false,
        connections: [],
        x: 0,
        y: 252,
      },
    ],
    stepDataByStateKey: {
      "2": {
        source: "Kaseya VSA, Sophos XDR, Sophos EDR",
        list: "Managed devices and agent health",
        code: "Identify devices not checking in, missing patches, unhealthy protection agents, and missing encryption coverage.",
      },
      "3": {
        operation: "Categorize and prioritize device findings",
        target: "Endpoint telemetry dataset",
        runtime: "Ivy Logic",
        code: "Separate operational issues from security issues, then rank by severity and business impact.",
      },
      "4": {
        action: "Send 'Devices needing attention' report grouped by severity.",
        channel: "Ivy Inbox",
        recipients: "IT Ops + Security",
        payload: "Operational issues and security issues listed in separate sections.",
      },
    },
  }),
  "4": createFlow({
    steps: [
      {
        id: 2,
        stateKey: "2",
        type: "lookup",
        title: "Gather Device Risk Signals",
        builderTitle: "Gather Device Signals",
        sources: buildSources(["Kaseya VSA", "Sophos XDR", "Sophos EDR"]),
        ivySays: "This step collects correlated endpoint posture and threat signals.",
        detailsCollapsed: false,
        connections: [3],
        x: 0,
        y: 84,
      },
      {
        id: 3,
        stateKey: "3",
        type: "code",
        title: "Correlate High-Risk Patterns",
        rowKeys: ["Operation", "Target", "Code"],
        ivySays: "This logic creates a small list of devices with stacked risk indicators.",
        detailsCollapsed: false,
        connections: [4],
        x: 0,
        y: 168,
      },
      {
        id: 4,
        stateKey: "4",
        type: "alert",
        title: "Escalate Critical Devices",
        ivySays: "This alert sends only high-confidence risky-device cases for immediate review.",
        detailsCollapsed: false,
        connections: [],
        x: 0,
        y: 252,
      },
    ],
    stepDataByStateKey: {
      "2": {
        source: "Kaseya VSA, Sophos XDR, Sophos EDR",
        list: "Device posture + threat telemetry",
        code: "Collect encryption status, patch compliance, malware alerts, and backup coverage indicators per device.",
      },
      "3": {
        operation: "Identify compounded endpoint risk",
        target: "Correlated device signals",
        runtime: "Ivy Logic",
        code: "Flag devices matching high-risk combinations such as no encryption + malware alert or no patching + privileged user access.",
      },
      "4": {
        condition: "Device risk score is critical",
        severity: "High",
        channels: "Ivy Inbox + Email",
        recipients: "SOC + IT Operations",
      },
    },
  }),
  "5": createFlow({
    steps: [
      {
        id: 2,
        stateKey: "2",
        type: "lookup",
        title: "Pull Email Threat Signals",
        builderTitle: "Pull Email Threat Signals",
        sources: buildSources(["Avanon", "KnowBe4"]),
        ivySays: "This step captures phishing activity and user susceptibility signals.",
        detailsCollapsed: false,
        connections: [3],
        x: 0,
        y: 84,
      },
      {
        id: 3,
        stateKey: "3",
        type: "code",
        title: "Detect Targeting Patterns",
        rowKeys: ["Operation", "Target", "Code"],
        ivySays: "This logic distinguishes targeted campaigns from broad spray attempts.",
        detailsCollapsed: false,
        connections: [4],
        x: 0,
        y: 168,
      },
      {
        id: 4,
        stateKey: "4",
        type: "message",
        title: "Share Exposure Summary",
        ivySays: "This step sends actionable exposure insights and suggested follow-up actions.",
        detailsCollapsed: false,
        connections: [],
        x: 0,
        y: 252,
      },
    ],
    stepDataByStateKey: {
      "2": {
        source: "Avanon, KnowBe4",
        list: "Phishing events and simulation outcomes",
        code: "Pull blocked phishing/malware, post-delivery remediation events, repeat user targeting, and simulation failures.",
      },
      "3": {
        operation: "Rank users by email threat exposure",
        target: "Email security signal set",
        runtime: "Ivy Logic",
        code: "Correlate repeated targeting and training outcomes to identify elevated risk users and likely campaign patterns.",
      },
      "4": {
        action: "Send daily email-risk digest with suggested actions.",
        channel: "Ivy Inbox",
        recipients: "Security Awareness Team",
        payload: "Include targeted vs random attack patterns and recommended controls/training follow-up.",
      },
    },
  }),
  "6": createFlow({
    steps: [
      {
        id: 2,
        stateKey: "2",
        type: "lookup",
        title: "Collect User Risk Signals",
        builderTitle: "Collect User Risk Signals",
        sources: buildSources(["Microsoft 365", "Avanon", "KnowBe4", "Sophos XDR"]),
        ivySays: "This lookup combines identity, phishing, and endpoint context for each user.",
        detailsCollapsed: false,
        connections: [3],
        x: 0,
        y: 84,
      },
      {
        id: 3,
        stateKey: "3",
        type: "code",
        title: "Build User Risk Ranking",
        rowKeys: ["Operation", "Target", "Code"],
        ivySays: "This logic explains the top user risks with confidence scoring.",
        detailsCollapsed: false,
        connections: [4],
        x: 0,
        y: 168,
      },
      {
        id: 4,
        stateKey: "4",
        type: "alert",
        title: "Escalate High-Risk Users",
        ivySays: "This alert escalates only users with meaningful, multi-signal risk.",
        detailsCollapsed: false,
        connections: [],
        x: 0,
        y: 252,
      },
    ],
    stepDataByStateKey: {
      "2": {
        source: "Microsoft 365, Avanon, KnowBe4, Sophos XDR",
        list: "User activity, exposure, and role context",
        code: "Collect privileged roles, weak auth indicators, phishing failures, malware exposure, and recent risky sign-ins.",
      },
      "3": {
        operation: "Rank users by overall risk",
        target: "Combined user risk dataset",
        runtime: "Ivy Logic",
        code: "Generate a ranked user list with plain-English rationale and a confidence indicator (High or Medium).",
      },
      "4": {
        condition: "User has high confidence risk score",
        severity: "High",
        channels: "Ivy Inbox + Email",
        recipients: "Security Team",
      },
    },
  }),
  "7": createFlow({
    steps: [
      {
        id: 2,
        stateKey: "2",
        type: "lookup",
        title: "Collect Network Risk Signals",
        builderTitle: "Collect Network Signals",
        sources: buildSources(["Cisco Meraki", "Cisco Umbrella"]),
        ivySays: "This step gathers network posture, DNS defense events, and access context.",
        detailsCollapsed: false,
        connections: [3],
        x: 0,
        y: 84,
      },
      {
        id: 3,
        stateKey: "3",
        type: "code",
        title: "Evaluate Exposure Conditions",
        rowKeys: ["Operation", "Target", "Code"],
        ivySays: "This logic identifies risky configurations and unusual access patterns.",
        detailsCollapsed: false,
        connections: [4],
        x: 0,
        y: 168,
      },
      {
        id: 4,
        stateKey: "4",
        type: "alert",
        title: "Notify on Network Risks",
        ivySays: "This alert surfaces meaningful network risks with suggested review questions.",
        detailsCollapsed: false,
        connections: [],
        x: 0,
        y: 252,
      },
    ],
    stepDataByStateKey: {
      "2": {
        source: "Cisco Meraki, Cisco Umbrella",
        list: "Network config and DNS security activity",
        code: "Pull weak/open SSID settings, repeated DNS security blocks, unexpected access locations, and recent config changes.",
      },
      "3": {
        operation: "Identify risky network exposure",
        target: "Network telemetry and change log",
        runtime: "Ivy Logic",
        code: "Flag high-risk patterns and summarize likely impact with a concise review checklist.",
      },
      "4": {
        condition: "Any network finding reaches medium or high severity",
        severity: "Medium",
        channels: "Ivy Inbox",
        recipients: "Network Team",
      },
    },
  }),
  "8": createFlow({
    steps: [
      {
        id: 2,
        stateKey: "2",
        type: "lookup",
        title: "Check Backup Coverage",
        builderTitle: "Check Backup Coverage",
        sources: buildSources(["Kaseya Spanning", "Microsoft 365"]),
        ivySays: "This step checks whether critical data and identities are actually protected.",
        detailsCollapsed: false,
        connections: [3],
        x: 0,
        y: 84,
      },
      {
        id: 3,
        stateKey: "3",
        type: "code",
        title: "Calculate Recovery Confidence",
        rowKeys: ["Operation", "Target", "Code"],
        ivySays: "This logic turns backup exceptions into a clear readiness confidence level.",
        detailsCollapsed: false,
        connections: [4],
        x: 0,
        y: 168,
      },
      {
        id: 4,
        stateKey: "4",
        type: "message",
        title: "Send Readiness Report",
        ivySays: "This step delivers a plain answer on recovery readiness and outstanding gaps.",
        detailsCollapsed: false,
        connections: [],
        x: 0,
        y: 252,
      },
    ],
    stepDataByStateKey: {
      "2": {
        source: "Kaseya Spanning, Microsoft 365",
        list: "Protected assets and backup job status",
        code: "Identify unprotected users/sites, recent backup failures, coverage gaps, and last successful backup timestamps.",
      },
      "3": {
        operation: "Assess backup and recovery readiness",
        target: "Backup coverage dataset",
        runtime: "Ivy Logic",
        code: "Produce 'Are we protected?' confidence result and list exceptions requiring follow-up.",
      },
      "4": {
        action: "Send backup readiness summary with confidence level.",
        channel: "Email",
        recipients: "IT Leadership + Security Team",
        payload: "Include protected coverage percentage, failed jobs, and top remediation priorities.",
      },
    },
  }),
  "9": createFlow({
    steps: [
      {
        id: 2,
        stateKey: "2",
        type: "lookup",
        title: "Aggregate Weekly Risk Signals",
        builderTitle: "Aggregate Weekly Signals",
        sources: buildSources(["Microsoft 365", "Sophos XDR", "Cisco Meraki", "Kaseya Spanning"]),
        ivySays: "This step pulls cross-system signals needed for a concise weekly leadership brief.",
        detailsCollapsed: false,
        connections: [3],
        x: 0,
        y: 84,
      },
      {
        id: 3,
        stateKey: "3",
        type: "action",
        title: "Generate Executive Narrative",
        ivySays: "This action composes the weekly story in plain language without alert noise.",
        detailsCollapsed: false,
        connections: [4],
        x: 0,
        y: 168,
      },
      {
        id: 4,
        stateKey: "4",
        type: "message",
        title: "Deliver Weekly Risk Brief",
        ivySays: "This message sends the final top-five risk brief to stakeholders.",
        detailsCollapsed: false,
        connections: [],
        x: 0,
        y: 252,
      },
    ],
    stepDataByStateKey: {
      "2": {
        source: "Microsoft 365, Sophos XDR, Cisco Meraki, Kaseya Spanning",
        list: "Cross-platform weekly security and IT activity",
        code: "Collect signal trends for risks, improvements, and material changes from connected tools.",
      },
      "3": {
        action: "Write a weekly brief with top 5 risks, what changed, what improved, and what needs attention. Use plain English and avoid vendor-heavy wording.",
      },
      "4": {
        action: "Send weekly security and IT risk brief.",
        channel: "Email",
        recipients: "Leadership Team",
        payload: "Top 5 risks, notable changes, improvements, and recommended follow-ups.",
      },
    },
  }),
};

export function getMockAssistantFlowById(assistantId) {
  const normalizedId = String(assistantId || "").trim();
  if (!normalizedId) {
    return DEFAULT_ASSISTANT_FLOW;
  }

  return MOCK_ASSISTANT_FLOWS_BY_ID[normalizedId] || DEFAULT_ASSISTANT_FLOW;
}
