export const mockAssistantInsights = [
  {
    id: "ins-1",
    assistantId: 1,
    title: "Admin account without MFA",
    summary: "Three privileged users currently hold admin roles without MFA enforced.",
    severity: "Critical",
    status: "New",
    sourceLabels: ["Microsoft 365"],
    affectedObject: "3 privileged users",
    confidence: "High",
    detectedAt: "Mar 19, 2026 • 8:42 AM",
  },
  {
    id: "ins-2",
    assistantId: 4,
    title: "High-risk endpoint cluster",
    summary: "LAPTOP-22 and 2 additional endpoints show malware alerts while encryption is disabled.",
    severity: "Risk",
    status: "In Review",
    sourceLabels: ["Kaseya VSA", "Sophos"],
    affectedObject: "3 devices",
    confidence: "High",
    detectedAt: "Mar 19, 2026 • 7:58 AM",
  },
  {
    id: "ins-3",
    assistantId: 3,
    title: "Critical patch backlog expanding",
    summary: "Twelve managed devices are missing critical patches for longer than seven days.",
    severity: "Warning",
    status: "New",
    sourceLabels: ["Kaseya VSA", "Sophos"],
    affectedObject: "12 devices",
    confidence: "Medium",
    detectedAt: "Mar 18, 2026 • 6:11 PM",
  },
  {
    id: "ins-4",
    assistantId: 8,
    title: "Backup coverage gap detected",
    summary: "Two Microsoft 365 users currently have no active backup coverage configured.",
    severity: "Risk",
    status: "New",
    sourceLabels: ["Kaseya Spanning", "Microsoft 365"],
    affectedObject: "2 user mailboxes",
    confidence: "High",
    detectedAt: "Mar 18, 2026 • 3:24 PM",
  },
  {
    id: "ins-5",
    assistantId: 5,
    title: "Targeted phishing pattern",
    summary: "Finance team users received repeated credential-harvest attempts across two campaigns.",
    severity: "Warning",
    status: "Acknowledged",
    sourceLabels: ["Avanan", "KnowBe4"],
    affectedObject: "Finance group",
    confidence: "Medium",
    detectedAt: "Mar 17, 2026 • 4:53 PM",
  },
  {
    id: "ins-6",
    assistantId: 9,
    title: "Weekly risk trend improved",
    summary: "Overall risk posture improved week-over-week, but identity risk remains the top concern.",
    severity: "Info",
    status: "New",
    sourceLabels: ["Microsoft 365", "Sophos", "Cisco Meraki"],
    affectedObject: "Org-wide posture",
    confidence: "Medium",
    detectedAt: "Mar 17, 2026 • 9:00 AM",
  },
];
